// frontend/src/app/shared/components/stat-card/stat-card.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

@Component({
  selector: 'app-stat-card',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <article class="surface p-4 sm:p-5">
      <div class="flex items-start justify-between gap-4">
        <div>
          <p class="text-sm font-medium text-stone-500">{{ label() }}</p>
          <p class="mt-2 text-2xl font-semibold tracking-tight text-stone-950">
            {{ value() }}
          </p>
        </div>
        <div
          class="flex size-11 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700 ring-1 ring-emerald-100"
        >
          <ng-content />
        </div>
      </div>
      <p class="mt-4 text-sm text-stone-500">{{ caption() }}</p>
    </article>
  `,
})
export class StatCardComponent {
  readonly label = input.required<string>();
  readonly value = input.required<string>();
  readonly caption = input<string>('');
}

// frontend-next/components/stat-card.tsx
import { cn } from "@/lib/utils"

interface StatCardProps {
  label: string
  value: string
  sub?: string
  icon?: React.ReactNode
  accent?: boolean
}

export function StatCard({ label, value, sub, icon, accent }: StatCardProps) {
  return (
    <div
      className={cn(
        "rounded-2xl p-4 shadow-sm border",
        accent
          ? "bg-primary text-primary-foreground border-primary"
          : "bg-card text-card-foreground border-border"
      )}
    >
      <div className="flex items-start justify-between gap-2">
        <p className={cn("text-xs font-medium uppercase tracking-wide", accent ? "text-primary-foreground/70" : "text-muted-foreground")}>
          {label}
        </p>
        {icon && (
          <div className={cn("w-8 h-8 rounded-xl flex items-center justify-center shrink-0", accent ? "bg-primary-foreground/15" : "bg-muted")}>
            {icon}
          </div>
        )}
      </div>
      <p className={cn("text-3xl font-bold mt-2 leading-none", accent ? "text-primary-foreground" : "text-foreground")}>
        {value}
      </p>
      {sub && (
        <p className={cn("text-xs mt-1.5", accent ? "text-primary-foreground/60" : "text-muted-foreground")}>
          {sub}
        </p>
      )}
    </div>
  )
}
